import Header from "@/components/Global/Header";
import Footer from "@/components/Global/Footer";
import { ThemeProvider } from "@/contex/ThemeContext"; // Import ThemeProvider
import "../styles/globals.css";
import '../styles/font.css';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="transition-colors duration-500">
        <ThemeProvider> {/* Wrap entire app */}
          <Header />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
