import Header from "@/components/Global/Header";
import Footer from "@/components/Global/Footer";
import { ThemeProvider } from "@/contex/ThemeContext"; // Import ThemeProvider
import "../styles/globals.css";

import Head from 'next/head';
// e.g., in layout.tsx or any top-level file
import { Space_Grotesk } from 'next/font/google';
import CustomCursor from "@/components/CustomCursor";

const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  variable: '--font-space-grotesk',
  weight: ['300', '400', '500', '600', '700'],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    
    <html lang="en" className={spaceGrotesk.variable}>
        <Head>
        {/* Google Fonts Embed */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        <link
          href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300..700&display=swap"
          rel="stylesheet"
        />
      </Head>
    
      <body className="transition-colors duration-500" style={{ fontFamily: 'Space Grotesk' }}>
        <ThemeProvider> {/* Wrap entire app */}
          <CustomCursor/>
          <Header />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
    
  );
}
